version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-django_db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
    ports:
      - "${DB_PORT:-5432}:5432"

  redis:
    image: redis:7-alpine
    container_name: redis_broker

  django:
    build: ./django_api
    container_name: django_api
    # Если в .env нет DJANGO_COMMAND, запустится runserver (для Dev)
    command: ${DJANGO_COMMAND:-python manage.py runserver 0.0.0.0:8000}
    volumes:
      - ./django_api:/app
      - django_static:/app/static # Добавляем это
      - django_media:/app/media # И это (для картинок)
    ports:
      - "${DJANGO_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-django_db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_CHANNEL_ID=${ADMIN_CHANNEL_ID}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - YOOKASSA_API_KEY=${YOOKASSA_API_KEY}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}

  celery_worker:
    build: ./django_api
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./django_api:/app
    depends_on:
      - django
      - redis
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-django_db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_CHANNEL_ID=${ADMIN_CHANNEL_ID}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - YOOKASSA_API_KEY=${YOOKASSA_API_KEY}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}

  celery_beat:
    build: ./django_api
    container_name: celery_beat
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./django_api:/app
    depends_on:
      - django
      - redis
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-django_db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_CHANNEL_ID=${ADMIN_CHANNEL_ID}
      - YOOKASSA_API_KEY=${YOOKASSA_API_KEY}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}

  bot:
    build: ./bot
    container_name: aiogram_bot
    # На Dev использует watchfiles, на Prod — команду из .env
    command: ${BOT_COMMAND:-watchfiles --filter python "python main.py"}
    volumes:
      - ./bot:/app
    depends_on:
      - django
    environment:
      - API_URL=${DJANGO_API_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEB_APP_URL=${WEB_APP_URL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}

  miniapp:
    build: ./miniapp
    container_name: nextjs_app
    # На Dev запустит npm run dev, на Prod — билд и старт
    command: ${MINIAPP_COMMAND:-npm run dev}
    volumes:
      - ./miniapp:/app
      - /app/node_modules
    ports:
      - "${MINIAPP_PORT:-3000}:3000"
    depends_on:
      - redis
      - django
    environment:
      - BOT_TOKEN=${TELEGRAM_TOKEN}
      - DJANGO_API_URL=${DJANGO_API_URL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - TARIFFS=${TARIFFS}

volumes:
  postgres_data:
  django_static:
  django_media:
