# Generated by Django 5.2.8 on 2026-02-14 09:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sub_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('xray_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('preshared_key', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('invited_bonus_given', models.BooleanField(default=False)),
                ('traffic_bonus_given', models.BooleanField(default=False)),
                ('invited_by', models.BigIntegerField(blank=True, null=True)),
                ('traffic_on', models.BooleanField(default=False)),
                ('autopay_enabled', models.BooleanField(default=False, verbose_name='Автопродление включено')),
                ('payment_method_id', models.CharField(blank=True, help_text='Токен для рекуррентных платежей от провайдера', max_length=255, null=True)),
                ('last_payment_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сервера')),
                ('api_url', models.CharField(help_text='Напр: http://1.2.3.4:2053', max_length=255)),
                ('api_username', models.CharField(blank=True, max_length=100, null=True)),
                ('api_password', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('amnezia', 'AmneziaWG'), ('xray', '3x-ui')], default='xray', max_length=20)),
                ('inbound_id', models.IntegerField(blank=True, help_text='ID инбаунда для 3x-ui (только для серверов типа xray)', null=True)),
                ('is_relay', models.BooleanField(default=False, help_text='Если включено, трафик будет идти через этот сервер к основному', verbose_name='Это транзитный сервер (РФ)')),
                ('upstream_server', models.ForeignKey(blank=True, help_text='Укажите основной сервер, на который этот сервер должен пересылать трафик', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relays', to='myapp.server', verbose_name='Целевой сервер (Европа)')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('months', models.IntegerField()),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('unique_payload', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('up_traff', models.BigIntegerField(default=0, verbose_name='Загружено (байты)')),
                ('down_traff', models.BigIntegerField(default=0, verbose_name='Скачано (байты)')),
                ('total_traff', models.BigIntegerField(default=0, verbose_name='Всего (байты)')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последнее подключение')),
                ('traffic_offset', models.BigIntegerField(default=0)),
                ('inbound_id', models.IntegerField(blank=True, help_text='ID инбаунда в панели 3x-ui', null=True)),
                ('client_email', models.CharField(blank=True, help_text='Email клиента в панели (используется как ID для API)', max_length=100, null=True)),
                ('vless_url', models.TextField(blank=True, null=True, verbose_name='Готовая ссылка vless://')),
                ('wg_conf_enpoint', models.TextField(blank=True, null=True)),
                ('wg_conf', models.TextField(blank=True, null=True)),
                ('wg_conf_ip', models.TextField(blank=True, null=True)),
                ('wg_conf_old_server', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='myapp.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='myapp.telegramuser')),
            ],
        ),
    ]
