# Generated by Django 5.2.8 on 2026-01-04 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('amnezia', 'AmneziaWG'), ('xray', '3x-ui')], max_length=20)),
                ('api_username', models.CharField(blank=True, max_length=100, null=True)),
                ('api_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('xray_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('preshared_key', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('invited_bonus_given', models.BooleanField(default=False)),
                ('traffic_bonus_given', models.BooleanField(default=False)),
                ('invited_by', models.BigIntegerField(blank=True, null=True)),
                ('traffic_on', models.BooleanField(default=False)),
                ('autopay_enabled', models.BooleanField(default=False, verbose_name='Автопродление включено')),
                ('payment_method_id', models.CharField(blank=True, help_text='Токен для рекуррентных платежей от провайдера', max_length=255, null=True)),
                ('last_payment_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('months', models.IntegerField()),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('unique_payload', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wg_conf', models.TextField(blank=True, null=True)),
                ('vless_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='myapp.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='myapp.telegramuser')),
            ],
        ),
    ]
