# Generated by Django 5.2.8 on 2026-02-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='server',
        ),
        migrations.AddField(
            model_name='credential',
            name='wg_conf_enpoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='wg_conf_ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='wg_conf_old_server',
            field=models.BooleanField(default=False),
        ),
    ]
