# Generated by Django 5.2.8 on 2026-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='Если True, пользователь считается родственником/другом, подписка бесплатная', verbose_name='Подарочная подписка'),
        ),
    ]
