# Generated by Django 5.2.8 on 2026-02-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_telegramuser_is_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='base_weight',
            field=models.FloatField(default=1.0, help_text='Используется для балансировки нагрузки', verbose_name='Вес сервера'),
        ),
        migrations.AddField(
            model_name='server',
            name='current_load',
            field=models.FloatField(default=0.0, verbose_name='Текущая нагрузка'),
        ),
        migrations.AddField(
            model_name='server',
            name='max_clients',
            field=models.IntegerField(default=1000),
        ),
    ]
