# Generated by Django 5.2.8 on 2026-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_server_base_weight_server_current_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='card_last4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
